.PHONY: clean All

All:
	@echo "----------Building project:[ count_bits_1_to_n - Debug ]----------"
	@cd "count_bits_1_to_n" && "$(MAKE)" -f  "count_bits_1_to_n.mk"
clean:
	@echo "----------Cleaning project:[ count_bits_1_to_n - Debug ]----------"
	@cd "count_bits_1_to_n" && "$(MAKE)" -f  "count_bits_1_to_n.mk" clean
