.PHONY: clean All

All:
	@echo "----------Building project:[ Read_Columns_c - Debug ]----------"
	@cd "Read_Columns_c" && "$(MAKE)" -f  "Read_Columns_c.mk"
clean:
	@echo "----------Cleaning project:[ Read_Columns_c - Debug ]----------"
	@cd "Read_Columns_c" && "$(MAKE)" -f  "Read_Columns_c.mk" clean
