.PHONY: clean All

All:
	@echo "----------Building project:[ Insert_Node_in_Linked_List - Debug ]----------"
	@cd "Insert_Node_in_Linked_List" && "$(MAKE)" -f  "Insert_Node_in_Linked_List.mk"
clean:
	@echo "----------Cleaning project:[ Insert_Node_in_Linked_List - Debug ]----------"
	@cd "Insert_Node_in_Linked_List" && "$(MAKE)" -f  "Insert_Node_in_Linked_List.mk" clean
